
-- RECFERENCE Tables

DROP TABLE IF EXISTS REF_MEM_TYPE;

CREATE TABLE if not exists REF_MEM_TYPE
(
			 TYPE_ID 			  	BIGSERIAL  PRIMARY key NOT NULl,
			 MEM_TYPE 			  	varchar(30) NOT null,
			 unique (MEM_TYPE)
);


DROP TABLE IF EXISTS REF_GENDER;

CREATE TABLE REF_GENDER
(
			 GENDER_ID 				BIGSERIAL  PRIMARY key NOT NULl,
			 GENDER 				varchar(10) NOT null,
			 unique (GENDER)
);


DROP TABLE IF EXISTS REF_KYC_STATUS;

CREATE TABLE REF_KYC_STATUS
(
			 KYC_STATUS_ID 			BIGSERIAL  PRIMARY key NOT NULl,
			 KYC_STATUS 			VARCHAR(10) NOT null,
			 unique (kyc_status)
);


DROP TABLE IF EXISTS REF_COUNTRY;

CREATE TABLE IF NOT EXISTS REF_COUNTRY 
(
  			 CONT_ID 		 		BIGSERIAL  PRIMARY key NOT NULL,
  			 CONT_NAME_ISO2 		VARCHAR(2) NOT NULL,
   			 CONT_NAME 				varchar(80) NOT NULL,
  			 CONT_NAME_NICE 		varchar(80) NOT NULL,
  			 CONT_NAME_ISO3 		VARCHAR(3) NOT NULL,
  			 CONT_NUM_CODE 			int ,
  			 CONT_CODE 				int NOT NULL
);


DROP TABLE IF EXISTS REF_REGION;
CREATE TABLE REF_REGION
(
			 REG_ID 				BIGSERIAL  PRIMARY key NOT NULl,
			 PREFIX 				VARCHAR(4) NOT NULL,
			 COUNTRY 				VARCHAR (100) NOT NULL,
			 STATE 					VARCHAR(100) NOT NULL,
			 CITY			 		VARCHAR(100) NOT NULL,
			 ZIP 					INT NOT NULL
);

DROP TABLE IF EXISTS REF_PRE_IPO_LIST;
CREATE TABLE 		 REF_PRE_IPO_LIST
(
			PRE_IPO_ID 				BIGSERIAL  PRIMARY key NOT NULl,
			PRE_IPO_NAME 			VARCHAR(100) NOT NULL,
			COM_SEG 				VARCHAR(100) NOT NULL,
			ISIN_NUM 				VARCHAR(50),
			ACQ_PRICE_MIN 			NUMERIC(13, 4),
			ACQ_PRICE_MAX 			NUMERIC(13, 4),
			SELL_PRICE_MIN 			NUMERIC(13,4),
			SELL_PRICE_MIX 			NUMERIC(13,4)
) ;

DROP TABLE IF EXISTS REF_LOAN_TYPE;

CREATE TABLE 		 REF_LOAN_TYPE
(
			LOAN_TYPE_ID 			BIGSERIAL  PRIMARY key NOT NULl,
			LOAN_TYPE 				VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS REF_MUT_FUND;

CREATE TABLE 		 REF_MUT_FUND
(
			MUT_FUND_ID 			BIGSERIAL  PRIMARY key NOT NULl,
			MUT_FUND_HOUSE 			VARCHAR(100) NOT NULL,
			MUT_FUND_NAME 			VARCHAR (10) -- GROWTH/DIVIDEND

);

DROP TABLE IF EXISTS REF_MUT_FUND_PLAN;

CREATE TABLE 		 REF_MUT_FUND_PLAN
(
			MUT_PLAN_ID 			BIGSERIAL  PRIMARY key NOT NULl,
			MUT_FUND_PLAN 			VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS REF_INVESTMENT_TYPE;

CREATE TABLE 		 REF_INVESTMENT_TYPE
(
			INV_TYPE_ID 			BIGSERIAL  PRIMARY key NOT NULl,
			INV_TYPE 				VARCHAR(100) 
);

